package:
  name: pbp-test
  version: 1.1
source:
  path: ../src
build:
  number: 570
about:
  home: https://github.com/AnacondaRecipes/pbp-test-feedstock
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
extra:
  recipe-maintainers:
    - ansthomas
